// <auto-generated />
namespace ereditarycode.console.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DbEredity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbEredity));
        
        string IMigrationMetadata.Id
        {
            get { return "202305030840325_DbEredity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
